### ISSUE TITLE
Management server could not connect to agent after rebooting of RH

### ISSUE THREAD

**Issue by tjamakeev** [subutai-io/subos#107]
After rebooting resource host, management server could not connect to agent.
In logs we see:

```:SubutaiLogEvent{timeStamp=1458817528105, loggerName='io.subutai.core.hostregistry.impl.HostRegistryImpl', renderedMessage='Error checking host SubutaiHost{peerId=7D5BC3CE5822D5A34D5CCBD54F4E479B0EB4F5C6, lastHeartbeat=0}', stackTrace='javax.ws.rs.ProcessingException: java.net.NoRouteToHostException: NoRouteToHostException invoking http://10.10.10.121:7070/ping: No route to host
	at org.apache.cxf.jaxrs.client.AbstractClient.checkClientException(AbstractClient.java:557)
	at org.apache.cxf.jaxrs.client.AbstractClient.preProcessResult(AbstractClient.java:539)
	at org.apache.cxf.jaxrs.client.WebClient.doResponse(WebClient.java:1151)
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1101)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:894)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:865)
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:331)
	at org.apache.cxf.jaxrs.client.WebClient.get(WebClient.java:357)
	at io.subutai.core.hostregistry.impl.HostRegistryImpl.updateHost(HostRegistryImpl.java:307)
	at io.subutai.core.hostregistry.impl.HostRegistryImpl$2.run(HostRegistryImpl.java:287)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by soffokl** [comment]
RH gets new IP after reboot because Open vSwitch gives new MAC-adders for interface.
