### ISSUE TITLE
[CLI] Segmentation fault in subutai command on import of master

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#89]
```
(amd64)root@rh1458149609:~# subutai import master
Segmentation fault
INFO[2016-03-16 17:36:38] [Importing master]                           
INFO[2016-03-16 17:36:41] Connecting to local Kurjun, dial tcp 10.10.10.1:8551: i/o timeout 
INFO[2016-03-16 17:36:45] [Downloading master]                         
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x308643f4 pc=0x308643f4]

runtime stack:
runtime.throw(0xa0cee0, 0x2a)
	/usr/local/go/src/runtime/panic.go:530 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.freemcache.func1()
	/usr/local/go/src/runtime/mcache.go:98 +0x78

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f9f728488e0, 0x72, 0xc82018c148)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82016a060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82016a060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82016a000, 0xc82018c148, 0x1eb8, 0x1eb8, 0x0, 0x7f9f72843050, 0xc820010190)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82014c028, 0xc82018c148, 0x1eb8, 0x1eb8, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f9f6bfc0250, 0xc82014c028, 0xc820148068, 0xc82018c148, 0x1eb8, 0x1eb8, 0x4c90, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc82010c700, 0xc82018c148, 0x1eb8, 0x1eb8, 0x4c90, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).Read(0xc82013c540, 0xc82018c148, 0x1eb8, 0x1eb8, 0x4c90, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:197 +0x126
net/http/internal.(*chunkedReader).Read(0xc82013aa50, 0xc82018c148, 0x1eb8, 0x1eb8, 0x6148, 0x0, 0x0)
	/usr/local/go/src/net/http/internal/chunked.go:88 +0x139
net/http.(*body).readLocked(0xc8200f8480, 0xc820186000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:651 +0xa1
net/http.(*body).Read(0xc8200f8480, 0xc820186000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:643 +0x110
net/http.(*bodyEOFSignal).Read(0xc8200f84c0, 0xc820186000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1609 +0x26a
io.copyBuffer(0x7f9f72847358, 0xc820176010, 0x7f9f6bf80108, 0xc8200f84c0, 0xc820186000, 0x8000, 0x8000, 0x3408000, 0x0, 0x0)
	/usr/local/go/src/io/io.go:380 +0x247
io.Copy(0x7f9f72847358, 0xc820176010, 0x7f9f6bf80108, 0xc8200f84c0, 0xc8200f84c0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:350 +0x64
github.com/subutai-io/base/agent/cli.download(0xc8200db590, 0x2a, 0xc820162270, 0x27, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/subutai-io/base/agent/cli/import.go:94 +0x4cc
github.com/subutai-io/base/agent/cli.LxcImport(0x7ffe1284b6a4, 0x6, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/subutai-io/base/agent/cli/import.go:153 +0x75c
main.main.func10(0xc820092640)
	/home/ubuntu/go/src/subutai/main.go:109 +0x174
github.com/codegangsta/cli.Command.Run(0x970050, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9cafe0, 0x17, 0x0, ...)
	/home/ubuntu/go/src/github.com/codegangsta/cli/command.go:174 +0x1399
github.com/codegangsta/cli.(*App).Run(0xc8200923c0, 0xc82000a1e0, 0x3, 0x3, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/codegangsta/cli/app.go:187 +0x112b
main.main()
	/home/ubuntu/go/src/subutai/main.go:281 +0x4fd4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
syscall.Syscall6(0xe8, 0x4, 0xc82011fc24, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.EpollWait(0x4, 0xc82011fc24, 0x7, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:365 +0x89
gopkg.in/fsnotify%2ev1.(*fdPoller).wait(0xc8200c7000, 0xa4c400, 0x0, 0x0)
	/home/ubuntu/go/src/gopkg.in/fsnotify.v1/inotify_poller.go:85 +0xbd
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc820012550)
	/home/ubuntu/go/src/gopkg.in/fsnotify.v1/inotify.go:191 +0x1a8
created by gopkg.in/fsnotify%2ev1.NewWatcher
	/home/ubuntu/go/src/gopkg.in/fsnotify.v1/inotify.go:60 +0x3e2

goroutine 6 [select]:
github.com/subutai-io/base/agent/agent/container.(*pool).Watch.func1(0xc820012550)
	/home/ubuntu/go/src/github.com/subutai-io/base/agent/agent/container/pool.go:63 +0x84d
created by github.com/subutai-io/base/agent/agent/container.(*pool).Watch
	/home/ubuntu/go/src/github.com/subutai-io/base/agent/agent/container/pool.go:81 +0xb0

goroutine 18 [chan receive]:
net/http.(*Transport).getConn.func2.1(0xc8200dde60, 0xc8200ce180, 0xa4c988)
	/usr/local/go/src/net/http/transport.go:691 +0x48
created by net/http.(*Transport).getConn.func2
	/usr/local/go/src/net/http/transport.go:695 +0x70

goroutine 9 [IO wait]:
net.runtime_pollWait(0x7f9f72848a60, 0x77, 0x4c1d84)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820054680, 0x77, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitWrite(0xc820054680, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:82 +0x36
net.(*netFD).connect(0xc820054620, 0x0, 0x0, 0x7f9f72847b38, 0xc8200c7820, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/fd_unix.go:127 +0x28e
net.(*netFD).dial(0xc820054620, 0x7f9f72847af0, 0x0, 0x7f9f72847af0, 0xc8200db6e0, 0x0, 0xc800000000, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/sock_posix.go:137 +0x364
net.socket(0x9719a8, 0x3, 0x2, 0x1, 0x0, 0xc8200db600, 0x7f9f72847af0, 0x0, 0x7f9f72847af0, 0xc8200db6e0, ...)
	/usr/local/go/src/net/sock_posix.go:89 +0x429
net.internetSocket(0x9719a8, 0x3, 0x7f9f72847af0, 0x0, 0x7f9f72847af0, 0xc8200db6e0, 0x0, 0x0, 0x0, 0x1, ...)
	/usr/local/go/src/net/ipsock_posix.go:161 +0x153
net.dialTCP(0x9719a8, 0x3, 0x0, 0xc8200db6e0, 0x0, 0xc800000000, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/tcpsock_posix.go:171 +0x12b
net.dialSingle(0xc82008c240, 0x7f9f72847a60, 0xc8200db6e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:371 +0x40c
net.dialSerial.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:343 +0x75
net.dial(0x9719a8, 0x3, 0x7f9f72847a60, 0xc8200db6e0, 0xc8200495f0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/fd_unix.go:40 +0x60
net.dialSerial(0xc82008c240, 0xc8200e4ac0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:345 +0x751
net.(*Dialer).Dial(0xc820049868, 0x9719a8, 0x3, 0xc8200ddc88, 0xf, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:239 +0x512
net.Dial(0x9719a8, 0x3, 0xc8200ddc88, 0xf, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:193 +0x96
net/http.(*Transport).dial(0xc8200ce180, 0x9719a8, 0x3, 0xc8200ddc88, 0xf, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:661 +0x1d3
net/http.(*Transport).dialConn(0xc8200ce180, 0x0, 0xc8200ddc80, 0x5, 0xc8200ddc88, 0xf, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:758 +0x1e3d
net/http.(*Transport).getConn.func4(0xc8200ce180, 0x0, 0xc8200ddc80, 0x5, 0xc8200ddc88, 0xf, 0xc8200dde60)
	/usr/local/go/src/net/http/transport.go:702 +0x66
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:704 +0x262

goroutine 23 [select]:
net/http.(*persistConn).readLoop(0xc820148000)
	/usr/local/go/src/net/http/transport.go:1178 +0xd52
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 24 [select]:
net/http.(*persistConn).writeLoop(0xc820148000)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb
```

**Comment by akarasulu** [comment]
build on https://github.com/subutai-io/subos/commit/7ea9e35d208a2e8e9e7ac2c8aea754370230f42f

Went a little further on the second try:

```
(amd64)root@rh1458149609:~# subutai import master
INFO[2016-03-16 17:39:44] [Importing master]                           
INFO[2016-03-16 17:39:47] Connecting to local Kurjun, dial tcp 10.10.10.1:8551: i/o timeout 
INFO[2016-03-16 17:39:50] [Downloading master]                         
INFO[2016-03-16 17:40:15] [Unpacking template master]                  
INFO[2016-03-16 17:40:16] [Installing template master]                 
FATA[2016-03-16 17:40:20] Receiving delta master/deltas/opt.delta: At subvol master-opt
/apps/subutai/current/bin/btrfs: line 6:  1975 Segmentation fault      btrfs-main "$@"
, exit status 139 
```

**Comment by soffokl** [comment]
This was problem with whole system. Problem gone after restart.
